# Application configuration
# Directory where uploaded resume files are stored (relative to project root)
file.upload-dir=uploads

# --- Data Source (PostgreSQL on Render) ---
spring.datasource.url=jdbc:postgresql://dpg-d60nlj7pm1nc73ct5gag-a.oregon-postgres.render.com:5432/job_tracker_api
spring.datasource.username=job_tracker_api_user
spring.datasource.password=QqxYiGFlSxkn8NWTVzHCt2rHWlADtnxj
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
