# Application configuration
# Directory where uploaded resume files are stored (relative to project root)
file.upload-dir=uploads

# --- Data Source (PostgreSQL on Render) ---
spring.datasource.url=jdbc:postgresql://dpg-d6nqnqs50q8c73ahs65g-a.oregon-postgres.render.com:5432/job_tracker_db_yrpa
spring.datasource.username=job_tracker_db_yrpa_user
spring.datasource.password=AfjvS1MpIsuny5yPeXaGUNn2Vw9G04If
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
